import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Josefin_Sans as JosefinSans } from "next/font/google";

import "../globals.css";
import React from "react";

import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const josefinSans = JosefinSans({
  subsets: ["latin"],
  variable: "--font-josefin_sans",
});

export const metadata: Metadata = {
  title: "Medrepo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={cn(
          "relative h-full font-josefin_sans antialiased",
          josefinSans.variable
        )}
      >
        <main className="relative flex min-h-screen flex-col">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
